## Create ClusterIssuer Object
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: lan@rafay.co
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-http
    solvers:
    - http01:
        serviceType: ClusterIP
        ingress:
          class: nginx
